### ISSUE TITLE
Where do I get the google api key

### ISSUE THREAD

**Issue by SarvagyaGupta** [project-rakan/xayah#41]
`REACT_APP_GOOGLE_API_KEY=*YOUR_API_KEY_HERE*` <-- where do I find the key to use? Can you provide that to me?

**Comment by ColTo632** [comment]
This documentation was written with the intent that developers procured their own google maps API key for local testing. Please refer to the google maps api [documentaion](https://developers.google.com/maps/documentation/javascript/get-api-key). You can get a key for testing and debuging purposes for free without payment information.

For the purpose of peer review, As it is unlikely that you will continue to use your key going forward in the short term, I can provide you with a key. Please message me on slack so that I can send it to you without exposing it to source control.
